openapi: 3.0.0
info:
  title: Nemuru API
  version: '1.0'
  description: |-
    ![authentication-process](../assets/images/nemuru-logo.png)

    The Nemuru API allows you to create and manage Merchants and Loans.

    Nemuru API provides two different environments to interact with: `Integration` and `Production`. You can use `Integration` in test mode, which does not affect your live data or interact with our banking partners. The server, and corresponding API key used to [authenticate](03-authentication.md) the requests, determines whether is is live mode (`Production`) or test mode (`Integration`).
  contact:
    name: Enric from Nemuru
    email: enric.gilabert@nemuru.com
servers:
  - url: 'https://api.nemuru.io/v1'
    description: Production
  - url: 'https://api-release.nemuru.io'
    description: Integration
paths:
  /api/financial/merchant/:
    get:
      summary: Get Merchants
      tags:
        - Merchants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status
                    example: ok
                  data:
                    type: array
                    description: ''
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                          example: ok
                          description: Status
                        payload:
                          $ref: ../models/Merchant.v1.yaml
              examples:
                Example:
                  value:
                    status: ok
                    data:
                      - status: ok
                        payload:
                          created_at: '2020-02-04T12:52:15+00:00'
                          updated_at: '2020-03-20T10:07:33+00:00'
                          id: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
                          registration_fields:
                            full_name:
                              first_name: Manolo
                              last_name: Lopez
                            phone_number: '+34626901301'
                            email: pinturas.manolo@nemuru.com
                            business_type:
                              business_type: freelance
                              declared_business_type: self-employed
                            business_name: Pinturas Manolo
                            amount_of_employees: '0_3'
                            category: other
                            postal_code: 8025
                            turnover: 0K_300K
                            corporate_id_number: B000012
                          status: status_documents_completed
                          approval_status:
                            is_approved_by_commercial: true
                            is_approved_by_risk: true
                          loan_programs:
                            - name: zero_program
                            - name: free_program
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-financial-merchant
      description: Gets the list of all Merchants.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          required: true
          description: Authorization
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
    post:
      summary: Create Merchant
      tags:
        - Merchants
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
      operationId: post-api-financial-merchant
      description: |-
        Creates a Merchant.

        <!-- theme: danger -->
        > **Phone number** and **email address** must be unique

        In case you created a Merchant with the wrong parameters, please let us know @@
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The Merchant id
                  format: uuid
                  example: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
                merchant_first_name:
                  type: string
                  description: The Merchant first name
                  example: Manolo
                merchant_last_name:
                  type: string
                  description: The Merchant last name
                  example: Lopez
                merchant_phone_number:
                  type: string
                  description: The Merchant phone number
                  example: '+34626901301'
                merchant_email:
                  type: string
                  description: The Merchant email
                  format: email
                  example: pinturas.manolo@nemuru.com
                merchant_declared_business_type:
                  type: string
                  enum:
                    - self-employed
                    - ltd
                  example: self-employed
                  description: The Merchant declared business type
                merchant_business_name:
                  type: string
                  example: Pinturas Manolo
                  description: The Merchant business name
                merchant_amount_of_employees:
                  type: string
                  description: The Merchant amount of employees
                  enum:
                    - '0_3'
                    - '3_10'
                    - '10_20'
                    - 20_PLUS
                  example: '0_3'
                merchant_category:
                  type: string
                  description: The Merchant category
                  enum:
                    - bathrooms
                    - kitchen
                    - whole_house
                    - buildings
                    - architecture
                    - decoration_and_design
                    - eco_improvement_and_solar_panels
                    - real_estate_and_rentals
                    - warehouse
                    - painting
                    - carpentry
                    - home_staging
                    - structure_and_humidity
                    - installations
                    - pools
                    - elevators
                    - awnings
                    - gardening
                    - other
                    - cosmetic_surgery
                    - travels
                    - education_and_trainings
                    - car_service
                    - car_dealerships
                  example: other
                merchant_postal_code:
                  type: string
                  description: The Merchant postal code
                  example: 8025
                merchant_turnover:
                  type: string
                  description: The Merchant turnover
                  enum:
                    - 0K_300K
                    - 300K_1M
                    - 1M_2M
                    - 2M_5M
                    - 5M_plus
                  example: 0K_300K
                merchant_corporate_id_number:
                  type: string
                  description: The Merchant corporate id number
                  example: 47865965K
              required:
                - id
                - merchant_first_name
                - merchant_last_name
                - merchant_phone_number
                - merchant_email
                - merchant_declared_business_type
                - merchant_business_name
                - merchant_amount_of_employees
                - merchant_category
                - merchant_postal_code
                - merchant_turnover
                - merchant_corporate_id_number
            examples:
              Example:
                value:
                  id: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
                  merchant_first_name: Manolo
                  merchant_last_name: Lopez
                  merchant_phone_number: '+34626901301'
                  merchant_email: pinturas.manolo@nemuru.com
                  merchant_declared_business_type: self-employed
                  merchant_business_name: Pinturas Manolo
                  merchant_amount_of_employees: '0_3'
                  merchant_category: other
                  merchant_postal_code: 8025
                  merchant_turnover: 0K_300K
                  merchant_corporate_id_number: B000012
        description: ''
  /api/auth/login:
    post:
      summary: Create API Token
      tags:
        - Authentication
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    description: Token type
                    example: Bearer
                    type: string
                  refresh_token:
                    description: Refresh token
                    example: def50200d7cef7d466cc4132310b098f86721272d301aed4c97f7e34b1b7010f05e7a7fd819dac60ef3ac5ce312ee082eebb87d14c62974870cd93b9de0a2ea615e1e994b539fb81ffe6a468ae138c1a9651b7340d0f0f3f64a7e999db7880402921aee251f169e9bb47334e5a31c268b8d3edb72dbd6320b4f70e83d813ad1d49b2fdb004a92bc2f2ce53f0c995840b462032dfac8b186e9c5b7245e9d7d9aa7dcb84b306659ed4ee57bb184a1763fd142f173290e19d25c1ec3338db4d4e59f5f0f1ffa4645de32539d555476b88dc44540e69d34342a660a1e2d3c59cd3b5b9295888cc24f95bb35a204b40aae0a874f02bbdce3b0a30dc5ea875fef908e21a60eb870ec188e7de4427002dafd2636cacc3b4a1c58e6b5797f688316e29bdf369d1fb02aecded6adf1f45f2c01961fad9496b753c664a0975c1c0df283a4041b90c9a66d4325d4c37b6f0fb158c536f5b5503db02da2c5ea297791b55eccb90ecb57cfb96a06180a598b3a03e03c852be1252430d263aa18345279f5d5180eb2dffcf7df3c2b371e839eac90948c913c089f83af88e881fe4
                    type: string
                  access_token:
                    description: Access token
                    example: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVhOTQzNzFmNzkwYTMyNTFlZDcxYjBmMjA1NzJkYmRhMDM5ZTNiYjFjMDkxZmI5YWZjYjJjMjk2Y2Y4MDI4MjMxZGQyZTkyYzI0Zjk4ZjgwIn0.eyJhdWQiOiIyYTlhYzA2Mi1lOTRlLTRlMmQtYTUxNC1mMjYyMGY5NDAwOWUiLCJqdGkiOiI1YTk0MzcxZjc5MGEzMjUxZWQ3MWIwZjIwNTcyZGJkYTAzOWUzYmIxYzA5MWZiOWFmY2IyYzI5NmNmODAyODIzMWRkMmU5MmMyNGY5OGY4MCIsImlhdCI6MTU4NTEyODI1MCwibmJmIjoxNTg1MTI4MjUwLCJleHAiOjE1ODc4MDY2NTAsInN1YiI6InN1cGVyYWRtaW5AbmVtdXJ1LmNvbSIsInNjb3BlcyI6W119.R1cP6kgfDP_yCd90abyX6lg-RE5eFTWfR5jdL5dVUjRAeUAc6pwsR0Ov43qaIxeq2Y7H3w5NBz8Cllg92Vivs_1mSOT3eRMj4S7aoCO6KZPTEWyhWzREidXZpKFmFK-kd1ZPSSnmzBqWCu_Fr4NQBHxU35-T5vfxF4LP29OdaefKqDHCvUIpWzhLQEWvXdeZ6OIFwvwefOJkLDNSg-7q7MzVa9Bjdlt2ESVPi1-tsyrQ4mnuWQElpLIy36aapkT03Cbj9r1xXpxC-4Seqxt8TARGWlm8ojJaDrGb80_lVFwzEyU71tROdLipBC3n_-3WPourPk5rKNnzLbKVy9-jSg
                    type: string
                  expires_in:
                    description: Expires in
                    example: 2678400
                    type: int
              examples:
                Example:
                  value:
                    token_type: Bearer
                    expires_in: 2678400
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVhOTQzNzFmNzkwYTMyNTFlZDcxYjBmMjA1NzJkYmRhMDM5ZTNiYjFjMDkxZmI5YWZjYjJjMjk2Y2Y4MDI4MjMxZGQyZTkyYzI0Zjk4ZjgwIn0.eyJhdWQiOiIyYTlhYzA2Mi1lOTRlLTRlMmQtYTUxNC1mMjYyMGY5NDAwOWUiLCJqdGkiOiI1YTk0MzcxZjc5MGEzMjUxZWQ3MWIwZjIwNTcyZGJkYTAzOWUzYmIxYzA5MWZiOWFmY2IyYzI5NmNmODAyODIzMWRkMmU5MmMyNGY5OGY4MCIsImlhdCI6MTU4NTEyODI1MCwibmJmIjoxNTg1MTI4MjUwLCJleHAiOjE1ODc4MDY2NTAsInN1YiI6InN1cGVyYWRtaW5AbmVtdXJ1LmNvbSIsInNjb3BlcyI6W119.R1cP6kgfDP_yCd90abyX6lg-RE5eFTWfR5jdL5dVUjRAeUAc6pwsR0Ov43qaIxeq2Y7H3w5NBz8Cllg92Vivs_1mSOT3eRMj4S7aoCO6KZPTEWyhWzREidXZpKFmFK-kd1ZPSSnmzBqWCu_Fr4NQBHxU35-T5vfxF4LP29OdaefKqDHCvUIpWzhLQEWvXdeZ6OIFwvwefOJkLDNSg-7q7MzVa9Bjdlt2ESVPi1-tsyrQ4mnuWQElpLIy36aapkT03Cbj9r1xXpxC-4Seqxt8TARGWlm8ojJaDrGb80_lVFwzEyU71tROdLipBC3n_-3WPourPk5rKNnzLbKVy9-jSg
                    refresh_token: def50200d7cef7d466cc4132310b098f86721272d301aed4c97f7e34b1b7010f05e7a7fd819dac60ef3ac5ce312ee082eebb87d14c62974870cd93b9de0a2ea615e1e994b539fb81ffe6a468ae138c1a9651b7340d0f0f3f64a7e999db7880402921aee251f169e9bb47334e5a31c268b8d3edb72dbd6320b4f70e83d813ad1d49b2fdb004a92bc2f2ce53f0c995840b462032dfac8b186e9c5b7245e9d7d9aa7dcb84b306659ed4ee57bb184a1763fd142f173290e19d25c1ec3338db4d4e59f5f0f1ffa4645de32539d555476b88dc44540e69d34342a660a1e2d3c59cd3b5b9295888cc24f95bb35a204b40aae0a874f02bbdce3b0a30dc5ea875fef908e21a60eb870ec188e7de4427002dafd2636cacc3b4a1c58e6b5797f688316e29bdf369d1fb02aecded6adf1f45f2c01961fad9496b753c664a0975c1c0df283a4041b90c9a66d4325d4c37b6f0fb158c536f5b5503db02da2c5ea297791b55eccb90ecb57cfb96a06180a598b3a03e03c852be1252430d263aa18345279f5d5180eb2dffcf7df3c2b371e839eac90948c913c089f83af88e881fe4
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: post-api-auth-login
      description: Creates an API Token from your username and password.
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
      requestBody:
        content:
          application/json:
            schema:
              description: Login
              type: object
              properties:
                username:
                  type: string
                  description: Username
                  example: username@email.com
                password:
                  type: string
                  description: Password
                  example: '12345'
              required:
                - username
                - password
            examples:
              Example:
                value:
                  username: username@email.com
                  password: '12345'
          text/plain:
            schema:
              type: object
              properties: {}
        description: Login
  '/api/financial/merchant/{merchantId}/':
    parameters:
      - schema:
          type: string
          format: uuid
          example: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
        name: merchantId
        in: path
        required: true
        description: Merchant Id
    get:
      summary: Get Merchant by Id
      tags:
        - Merchants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                    description: Status
                  payload:
                    $ref: ../models/Merchant.v1.yaml
              examples:
                Example:
                  value:
                    status: ok
                    payload:
                      created_at: '2020-02-04T12:52:15+00:00'
                      updated_at: '2020-03-20T10:07:33+00:00'
                      id: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
                      registration_fields:
                        full_name:
                          first_name: Manolo
                          last_name: Lopez
                        phone_number: '+34626901301'
                        email: pinturas.manolo@nemuru.com
                        business_type:
                          business_type: freelance
                          declared_business_type: self-employed
                        business_name: Pinturas Manolo
                        amount_of_employees: '0_3'
                        category: other
                        postal_code: 8025
                        turnover: 0K_300K
                        corporate_id_number: B000012
                      status: status_documents_completed
                      approval_status:
                        is_approved_by_commercial: true
                        is_approved_by_risk: true
                      cash_in_cash_out_method_ids:
                        - e1f2afb4-01b7-4251-9b7a-30d1ea2f4b44
                      with_balance: false
                      segment: gold
                      loan_programs:
                        - name: zero_program
                        - name: free_program
                    identifier: 'urn:nemuru:financial:merchant:6fef65a6-1e5f-11e9-ab34-d662bd873d88'
        '400':
          description: ''
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                    description: Status
                  payload:
                    $ref: ../models/Merchant.v1.yaml
              examples:
                Example:
                  value:
                    status: ok
                    payload:
                      created_at: '2020-02-04T12:52:15+00:00'
                      updated_at: '2020-03-20T10:07:33+00:00'
                      id: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
                      registration_fields:
                        full_name:
                          first_name: Manolo
                          last_name: Lopez
                        phone_number: '+34626901301'
                        email: pinturas.manolo@nemuru.com
                        business_type:
                          business_type: freelance
                          declared_business_type: self-employed
                        business_name: Pinturas Manolo
                        amount_of_employees: '0_3'
                        category: other
                        postal_code: 8025
                        turnover: 0K_300K
                        corporate_id_number: B000012
                      status: status_documents_completed
                      approval_status:
                        is_approved_by_commercial: true
                        is_approved_by_risk: true
                      cash_in_cash_out_method_ids:
                        - e1f2afb4-01b7-4251-9b7a-30d1ea2f4b44
                      with_balance: false
                      segment: gold
                      loan_programs:
                        - name: zero_program
                        - name: free_program
                    identifier: 'urn:nemuru:financial:merchant:6fef65a6-1e5f-11e9-ab34-d662bd873d88'
          description: ''
      operationId: get-api-financial-merchant-merchantId
      description: Gets a Merchant by Id.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
  '/api/financial/merchant/{merchantId}/loan/':
    parameters:
      - schema:
          type: string
          format: uuid
          example: 6fef65a6-1e5f-11e9-ab34-d662bd873d88
        name: merchantId
        in: path
        required: true
        description: Merchant Id
    get:
      summary: Get Loans by Merchant Id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                    description: Status
                  payload:
                    $ref: ../models/Loan.v1.yaml
              examples:
                Example:
                  value:
                    status: ok
                    data:
                      - status: ok
                        payload:
                          created_at: '2020-03-23T12:33:55+00:00'
                          updated_at: '2020-03-23T12:33:55+00:00'
                          id: 1c5d6380-13c3-44c0-930e-9ea9f6090559
                          status: status_initial
                          loan_conditions:
                            currency: EUR
                            due_date: '1'
                            program: free_program
                            merchant_discount_percentage: '0.0'
                            annual_interest: '0.075'
                            principal: '8000.0'
                            setup_fee: '8000.0'
                            term: '30.0'
                            number_of_payments: '30'
                            tae: '0.075'
                            total_interest_paid: '8000.0'
                            total_amount_paid: '8000.0'
                            user_defined_quota: '235.0'
                          borrower_invitation:
                            email: john.doe@nemuru.com
                            full_name:
                              first_name: John
                              last_name: Doe
                            phone_number: '+34601000001'
                            borrower_invitation_expires_on: '2020-08-15T00:00:00+00:00'
                            total_budget: '10000.0'
                            job_description: Reformas de mi casa
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-financial-merchant-merchantId-loan
      description: Gets list of Loans from a Merchant by Id.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
      tags:
        - Loans
  /api/financial/loan/:
    post:
      summary: Creates a Loan
      tags:
        - Loans
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '409':
          description: Conflict
        '500':
          description: Internal Server Error
      operationId: post-api-financial-loan
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  example: e7c52ad3-0473-4fbc-bc36-7eb755b1c18d
                  description: The Loan id
                loan_conditions_currency:
                  type: string
                  example: EUR
                  description: The Loan conditions currency
                loan_conditions_user_conditions_term_period:
                  type: number
                  description: The Loan conditions user conditions term period
                  example: 30
                loan_conditions_loan_calculator_principal:
                  type: number
                  description: The Loan conditions loan calculator principal
                  example: 8000
                loan_conditions_program:
                  type: string
                  description: The Loan conditions program
                  enum:
                    - free_program
                    - zero_program
                  example: free_program
                loan_conditions_fee_amount:
                  type: number
                  description: The Loan conditions setup fee for the borrower
                  example: 20
                merchant_id:
                  type: string
                  description: The Loan merchant id
                  format: uuid
                  example: 9286898b-7bb7-4885-9a9b-94c4e880378b
                borrower_invitation_email:
                  type: string
                  format: email
                  example: john.doe@nemuru.com
                  description: The Loan borrower invitation email
                borrower_invitation_first_name:
                  type: string
                  example: John
                  description: The Loan borrower invitation first name
                borrower_invitation_last_name:
                  type: string
                  example: Doe
                  description: The Loan borrower invitation last name
                borrower_invitation_phone_number:
                  type: string
                  example: '+34601000001'
                  description: The Loan borrower invitation phone number
                borrower_invitation_total_budget_amount:
                  type: number
                  example: 10000
                  description: The Loan borrower invitation total budget amount
                borrower_invitation_job_description:
                  type: string
                  description: The Loan borrower invitation job description
                  example: Reformas de mi casa
              required:
                - id
                - loan_conditions_currency
                - loan_conditions_user_conditions_term_period
                - loan_conditions_loan_calculator_principal
                - loan_conditions_program
                - loan_conditions_fee_amount
                - merchant_id
                - borrower_invitation_email
                - borrower_invitation_first_name
                - borrower_invitation_last_name
                - borrower_invitation_phone_number
                - borrower_invitation_total_budget_amount
                - borrower_invitation_job_description
            examples:
              Example:
                value:
                  id: e7c52ad3-0473-4fbc-bc36-7eb755b1c18d
                  loan_conditions_currency: EUR
                  loan_conditions_user_conditions_term_period: '30.00'
                  loan_conditions_loan_calculator_principal: '8000.00'
                  loan_conditions_program: free_program
                  loan_conditions_fee_amount: '20.00'
                  merchant_id: 9286898b-7bb7-4885-9a9b-94c4e880378b
                  borrower_invitation_email: john.doe@nemuru.com
                  borrower_invitation_first_name: John
                  borrower_invitation_last_name: Doe
                  borrower_invitation_phone_number: '+34601000001'
                  borrower_invitation_total_budget_amount: '10000.00'
                  borrower_invitation_job_description: Reformas de mi casa
      description: Creates a Loan.
    get:
      summary: Get Loans
      tags:
        - Loans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status
                    example: ok
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: string
                          description: Status
                          example: ok
                        payload:
                          $ref: ../models/Loan.v1.yaml
                required:
                  - status
                  - data
              examples:
                Example:
                  value:
                    status: ok
                    data:
                      - status: ok
                        payload:
                          created_at: '2020-03-23T12:33:55+00:00'
                          updated_at: '2020-03-23T12:33:55+00:00'
                          id: 1c5d6380-13c3-44c0-930e-9ea9f6090559
                          status: status_initial
                          loan_conditions:
                            currency: EUR
                            due_date: '1'
                            program: free_program
                            merchant_discount_percentage: '0.0'
                            annual_interest: '0.075'
                            principal: '8000.0'
                            setup_fee: '8000.0'
                            term: '30.0'
                            number_of_payments: '30'
                            tae: '0.075'
                            total_interest_paid: '8000.0'
                            total_amount_paid: '8000.0'
                            user_defined_quota: '235.0'
                          borrower_invitation:
                            email: john.doe@nemuru.com
                            full_name:
                              first_name: John
                              last_name: Doe
                            phone_number: '+34601000001'
                            borrower_invitation_expires_on: '2020-08-15T00:00:00+00:00'
                            total_budget: '10000.0'
                            job_description: Reformas de mi casa
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-financial-loan
      description: Gets the list of all Loans.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
  '/api/financial/loan/{loanId}/':
    parameters:
      - schema:
          type: string
          format: uuid
          example: 1c5d6380-13c3-44c0-930e-9ea9f6090559
        name: loanId
        in: path
        required: true
        description: Loan Id
    get:
      summary: Get Loan by Id
      tags:
        - Loans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                    description: Status
                  payload:
                    type: object
                    properties:
                      payload:
                        $ref: ../models/Loan.v1.yaml
                required:
                  - status
                  - payload
              examples:
                Example:
                  value:
                    status: ok
                    payload:
                      created_at: '2020-03-23T12:33:55+00:00'
                      updated_at: '2020-03-23T12:33:55+00:00'
                      id: 1c5d6380-13c3-44c0-930e-9ea9f6090559
                      status: status_initial
                      loan_conditions:
                        currency: EUR
                        due_date: '1'
                        program: free_program
                        merchant_discount_percentage: '0.0'
                        annual_interest: '0.075'
                        principal: '8000.0'
                        setup_fee: '8000.0'
                        term: '30.0'
                        number_of_payments: '30'
                        tae: '0.075'
                        total_interest_paid: '8000.0'
                        total_amount_paid: '8000.0'
                        user_defined_quota: '235.0'
                      borrower_invitation:
                        email: john.doe@nemuru.com
                        full_name:
                          first_name: John
                          last_name: Doe
                        phone_number: '+34601000001'
                        borrower_invitation_expires_on: '2020-08-15T00:00:00+00:00'
                        total_budget: '10000.0'
                        job_description: Reformas de mi casa
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-financial-loan-loanId
      description: Gets a Loan by Id.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
  /api/financial/loan/conditions/:
    get:
      summary: Get Loan conditions
      tags:
        - Loans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    created_at:
                      type: string
                      description: Created at
                      format: date-time
                      example: '2020-03-23T12:33:55+00:00'
                    updated_at:
                      type: string
                      description: Updated at
                      format: date-time
                      example: '2020-03-23T12:33:55+00:00'
                    loan_conditions:
                      $ref: ../models/Loan-conditions.v1.yaml
              examples:
                Example:
                  value:
                    created_at: '2020-03-23T12:33:55+00:00'
                    updated_at: '2020-03-23T12:33:55+00:00'
                    loan_conditions:
                      currency: EUR
                      due_date: '1'
                      program:
                        name: free_program
                        merchant_discount_percentage:
                          value: '0.0'
                      annual_interest: '0.075'
                      principal:
                        currency: EUR
                        amount: '8000.0'
                      loan_calculator:
                        currency: EUR
                        setup_fee:
                          type: type_fixed_amount
                          fee_amount:
                            currency: EUR
                            amount: '8000.0'
                        term:
                          period: '30.0'
                          type: type_period
                          interval: P1M
                          number_of_payments: '30'
                        tae: '0.075'
                        total_interest_paid:
                          currency: EUR
                          amount: '8000.0'
                        total_amount_paid:
                          currency: EUR
                          amount: '8000.0'
                        user_defined_quota:
                          currency: EUR
                          amount: '8000.0'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-financial-loan-conditions
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
          required: false
        - schema:
            type: string
            example: 9286898b-7bb7-4885-9a9b-94c4e880378b
          in: query
          name: merchant_id
          description: The Merchant id
          required: true
        - schema:
            type: string
            example: EUR
          in: query
          name: currency
          description: The Loan currrency
          required: true
        - schema:
            type: number
            example: 30
          in: query
          name: term_period
          required: true
          description: The Loan term defined by the user
        - schema:
            type: number
            example: 8000
          in: query
          name: principal_amount
          description: The Loan principal amount
          required: true
        - schema:
            type: number
            example: 20
          in: query
          name: fee_amount
          description: The Loan setup fee amount
          required: true
      description: |-
        Gets the Loan conditions given a Merchant id and Loan parameters (principal, term, setup fee, and currrency).

        <!-- theme: info -->
        > This operations does not create a Loan, it only simulates and returns the conditions of a Loan with the principal, term, fee amount, and merchant (associated pricing) provided in the request.
  /api/healthcheck/ping:
    get:
      summary: Healthcheck
      tags:
        - Healthcheck
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      operationId: get-api-healthcheck-ping
      description: Gets the operational status of the API.
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
  /api/financial/merchant/allowed/categories/:
    get:
      summary: Get Merchant categories
      tags:
        - Merchants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                Example:
                  value:
                    - bathrooms
                    - kitchen
                    - whole_house
                    - buildings
                    - architecture
                    - decoration_and_design
                    - eco_improvement_and_solar_panels
                    - real_estate_and_rentals
                    - warehouse
                    - painting
                    - carpentry
                    - home_staging
                    - structure_and_humidity
                    - installations
                    - pools
                    - elevators
                    - awnings
                    - gardening
                    - other
                    - cosmetic_surgery
                    - travels
                    - education_and_trainings
                    - car_service
                    - car_dealerships
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-api-financial-merchant-allowed-categories
      description: Gets the allowed Merchant categories.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Authorization
          required: true
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: Content-Type
components:
  schemas: {}
  securitySchemes:
    API Key:
      type: oauth2
      flows:
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
